import type { Metadata } from "next";
import "./globals.css";
import NavWrapper from "@/components/NavWrapper";
import { fontThemeClassName } from "@/theme/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import CartDrawer from "@/components/CartDrawer";
import SmoothScrollProvider from "@/components/SmoothScrollProvider";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${fontThemeClassName} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <SmoothScrollProvider />
        <NavWrapper>
          {children}
        </NavWrapper>
        <CartDrawer />
      </body>
    </html>
  );
}
