import type { Metadata } from "next";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import NavWrapper from "@/components/NavWrapper";
import { fontThemeClassName } from "@/theme/fonts";
import CartDrawer from "@/components/CartDrawer";
import SmoothScrollProvider from "@/components/SmoothScrollProvider";
import PageLoader from "@/components/PageLoader";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html
        lang="en"
        className={`${fontThemeClassName} h-full antialiased`}
      >
        <body className="min-h-full flex flex-col">
          <PageLoader />
          <SmoothScrollProvider />
          <NavWrapper>
            {children}
          </NavWrapper>
          <CartDrawer />
        </body>
      </html>
    </ClerkProvider>
  );
}
